### ISSUE TITLE
Multiple StackSets in one Stack with assetBucket

### ISSUE THREAD

**Issue by boenhoff** [cdklabs/cdk-stacksets#257]
I want to create multiple StackSets in one Stack. I tried to deploy the following CDK Stack:
<details><summary>CDK Stack</summary>
<p>

```
import { Stack, StackProps } from 'aws-cdk-lib';
import { NodejsFunction } from 'aws-cdk-lib/aws-lambda-nodejs';
import { RetentionDays } from 'aws-cdk-lib/aws-logs';
import { Bucket } from 'aws-cdk-lib/aws-s3';
import { Capability, DeploymentType, StackSet, StackSetStack, StackSetTarget, StackSetTemplate } from 'cdk-stacksets';
import { Construct } from 'constructs';
import { config } from '../config';

export class TestStack extends Stack {

  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const assetBucket = Bucket.fromBucketName(this, 'SomeBucketForAssets', config.bucketName);

    const firstStackSet = new StackSetStack(this, 'FirstStackSet', {
      assetBucket: assetBucket,
    });
    new NodejsFunction(firstStackSet, 'FirstStackSetLambda', {
      logRetention: RetentionDays.THREE_DAYS,
      entry: './src/lambda/index.ts',
      depsLockFilePath: './src/lambda/package-lock.json',
    });
    new StackSet(this, 'FirstStackSetDeployment', {
      target: StackSetTarget.fromOrganizationalUnits({
        regions: config.stackSetRegions,
        organizationalUnits: config.stackSetOrganizationalUnits,
        excludeAccounts: [config.cloudformationAccountId],
      }),
      deploymentType: DeploymentType.serviceManaged(),
      capabilities: [Capability.IAM],
      template: StackSetTemplate.fromStackSetStack(firstStackSet),
    });

    const secondStackSet = new StackSetStack(this, 'SecondStackSet', {
      assetBucket: assetBucket,
    });
    new NodejsFunction(secondStackSet, 'SecondStackSetLambda', {
      logRetention: RetentionDays.THREE_DAYS,
      entry: './src/lambda/index.ts',
      depsLockFilePath: './src/lambda/package-lock.json',
    });
    new StackSet(this, 'SecondStackSetDeployment', {
      target: StackSetTarget.fromOrganizationalUnits({
        regions: config.stackSetRegions,
        organizationalUnits: config.stackSetOrganizationalUnits,
        excludeAccounts: [config.cloudformationAccountId],
      }),
      deploymentType: DeploymentType.serviceManaged(),
      capabilities: [Capability.IAM],
      template: StackSetTemplate.fromStackSetStack(secondStackSet),
    });
  }
}
```

</p>
</details> 

<details><summary>Error</summary>
<p>

```
/redacted/app/node_modules/constructs/src/construct.ts:428
      throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
            ^
Error: There is already a Construct with name 'StackSetAssetsBucketDeployment' in TestStack [TestStack]
    at Node.addChild (/redacted/app/node_modules/constructs/src/construct.ts:428:13)
    at new Node (/redacted/app/node_modules/constructs/src/construct.ts:71:17)
    at new Construct (/redacted/app/node_modules/constructs/src/construct.ts:480:17)
    at new BucketDeployment (/redacted/app/node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:803)
    at StackSetStackSynthesizer.addFileAsset (/redacted/app/node_modules/cdk-stacksets/src/stackset-stack.ts:59:32)
    at new Asset (/redacted/app/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:1207)
    at AssetCode.bind (/redacted/app/node_modules/aws-cdk-lib/aws-lambda/lib/code.js:1:4628)
    at new Function (/redacted/app/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:7510)
    at new NodejsFunction (/redacted/app/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/function.js:1:1215)
    at new TestStack (/redacted/app/src/Stacks/TestStack.ts:38:5)
```

</p>
</details> 

If I use one parent stack per StackSet it works of course. I'm doing something wrong or is that at the moment a limitation from this construct?

**Comment by mbergkvist** [comment]
Try put each `StackSetStack`, and it's resources, in separate `Construct`s. Should make `StackSetAssetsBucketDeployment` namespaced.

**Comment by josh-demuth** [comment]
i believe this will be resolved in https://github.com/cdklabs/cdk-stacksets/pull/325. this causes a breaking change to how the bucket is passed and named though.

**Comment by pahud** [comment]
Hi @boenhoff,

```
┌────────────────────────────────┐     ┌──────────────────────────────────────────┐
│ cdk-stacksets <= 0.0.149       │ ──> │ every StackSetStack creates its asset    │
│ two StackSetStacks, one Stack  │     │ BucketDeployment in the parent Stack as  │
│                                │     │ 'StackSetAssetsBucketDeployment'         │
└────────────────────────────────┘     └───────────────────┬──────────────────────┘
                                                           v
                                       ┌──────────────────────────────────────────┐
                                       │ duplicate construct id ──> synth error   │
                                       └──────────────────────────────────────────┘
┌────────────────────────────────┐     ┌──────────────────────────────────────────┐
│ PR #325 → v0.0.150 (2024-02-06)│ ──> │ id = <uniqueId(StackSetStack)>-          │
│                                │     │      AssetBucketDeployment-<n>  ✔        │
└────────────────────────────────┘     └──────────────────────────────────────────┘
```

Thanks for the report, and thanks @josh-demuth for the pointer. This was fixed by #325, released in cdk-stacksets v0.0.150 (2024-02-06). I confirmed it locally with `cdk synth`: two `StackSetStack`s with Lambda file assets in one `Stack` fail on 0.0.149 with exactly your error, and synthesize fine on the current 0.0.154 with two distinct `Custom::CDKBucketDeployment` resources and two stackset templates.

The cause was the hardcoded construct id used for every deployment:

https://github.com/cdklabs/cdk-stacksets/blob/fc05a068880ca98b9cac9f509a609be7a2c6bc55/src/stackset-stack.ts#L59-L68

It is now unique per `StackSetStack`:

https://github.com/cdklabs/cdk-stacksets/blob/51abb00f9e93224d3fb16835d34c0396eedf5a8f/src/stackset-stack.ts#L100-L113

Heads-up when upgrading: the same PR changed the props — `assetBucket: bucket` becomes `assetBuckets: [bucket]` plus a required `assetBucketPrefix`, and the bucket must be named `${assetBucketPrefix}-${region}`. (For anyone stuck on an old version, the "wrap each StackSetStack in a Construct" suggestion above does not help, since the deployment is always created under the parent `Stack`.)

From my view this can be closed as fixed. If it still reproduces on a current version, please reopen with the version numbers and the synth error.

**Comment by pahud** [comment]
Closing as fixed in v0.0.150 via #325. Feel free to reopen if there's any concern.
