### ISSUE TITLE
Cannot find asset with NodejsFunction created asset

### ISSUE THREAD

**Issue by mbergkvist** [cdklabs/cdk-stacksets#258]
I trying to deploy a `NodejsFunction` with a stackset but I can't get the file asset to work. I get the following error

> Error: Cannot find asset at /Users/markus/src/awsCore-tagScheduler/infrastructure/cdk.out/assembly-awsCoreTagScheduler-awsCoreTagScheduler-frankfurt-dev/Users/markus/src/awsCore-tagScheduler/infrastructure

It looks like it's adding the asset directory as source to the `bucketDeployment` instead of the asset filename. Can't figure out why though.

## How to reproduce

A simplified example of what I'm trying to accomplish, more or less following the example in the project README.

```typescript
export class TagSchedulerStage extends Stage {
  constructor(
    scope: Construct,
    id: string,
    props: StageProps,
  ) {
    super(scope, id, props);

    const bucketStack = new Stack(this, 'BucketStack');
    const bucket = new s3.Bucket(bucketStack, 'Assets', {
      bucketName: 'cdkstacket-asset-bucket-xyz',
    });
    bucket.addToResourcePolicy(
      new iam.PolicyStatement({
        actions: ['s3:Get*', 's3:List*'],
        resources: [bucket.arnForObjects('*'), bucket.bucketArn],
        principals: [new iam.OrganizationPrincipal('ou-ab12')],
      }),
    );

    const stack = new Stack(this, 'TopLevelStack');

    const stackSetStack = new StackSetStack(stack, 'MyStackSetStack', {
      assetBucket: bucket,
    });

    new lambdaNodejs.NodejsFunction(
      stackSetStack,
      'MyLambdaHandler',
      {
        handler: 'handler',
        entry: path.join(__dirname, '../../src/function.ts'),
      },
    );

    new StackSet(stack, 'MyStackSet', {
      capabilities: [Capability.IAM],
      deploymentType: DeploymentType.serviceManaged(),
      target: StackSetTarget.fromAccounts({
        regions: ['eu-central-1'],
        accounts: ['123456789012'],
      }),
      template: StackSetTemplate.fromStackSetStack(stackSetStack),
    });
  }
}
```

Any advice?

**Comment by mbergkvist** [comment]
I have put up an example application here, https://github.com/mbergkvist/stacksetsandassets

The command I execute is

```shell
npm run cdk list
```

and the error is

```shell
Error: Cannot find asset at /Users/markus/tmp/stacksetsandassets/cdk.out/Users/markus/tmp/stacksetsandassets
```

**Comment by mbergkvist** [comment]
Some updates:

- `npm run cdk synth -- --all` works fine
- I get the exact same error with `RustFunction`
- `PythonFunction` works without any reported error for both `cdk synth` and `cdk list`, but instead it fails with uploading the lambda asset with the wrong key, making the stack deployed by the stackset fail. The example in https://github.com/mbergkvist/stacksetsandassets is updated to include PythonFunction.

**Comment by josh-demuth** [comment]
i tested something similar with the recent updates from https://github.com/cdklabs/cdk-stacksets/pull/325 and it seems to work OK. once we can get this merged please test again and we can address if still having issues.

**Comment by josh-demuth** [comment]
thanks for reporting this. i tested a nodejs function with the recent updates in https://github.com/cdklabs/cdk-stacksets/pull/325 and it seems to work OK. there is an issue with python lambda with the s3 asset file name that gets produced that we will look into.

**Comment by mbergkvist** [comment]
> thanks for reporting this. i tested a nodejs function with the recent updates in #325 and it seems to work OK. there is an issue with python lambda with the s3 asset file name that gets produced that we will look into.

I'll take #325 for a spin on my example repo, testing it with both nodejs function and Rust function.

**Comment by mbergkvist** [comment]
@josh-demuth Tested #325 with the project in https://github.com/mbergkvist/stacksetsandassets/pull/1 but I still get the same error. It looks like it's adding the asset directory as source to the bucketDeployment instead of the asset filename.

**Comment by josh-demuth** [comment]
yes was testing more and sometimes it would work and sometimes not. the s3 bucket deployment process is getting a different hash. the lambda asset process creates a directory and not a zip at this stage of the process. are you seeing a .zip file be created in your cdk.out?

**Comment by mbergkvist** [comment]
There is a zip-file _asset.3322b7049fb0ed2b7cbb644a2ada8d1116ff80c32dca89e6ada846b5de26f961.zip_. The content of the file is the `awscli`, not the lambda-code. There is also a folder _asset.e976a796f036a5efbf44b99e44cfb5a961df08d8dbf7cd37e60bf216fb982a00_ with a Python script that looks like a Custom Resource handler, I assume it comes from the CDK.

**Comment by mgroff2** [comment]
I found this thread with high hopes until I clicked and saw it was still open. I am too experienceing this issue. 

```
Error: Cannot find asset at /Users/mypath/cdk.out/Users/mypath
    at new AssetStaging (/Users/mypath/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2119)
    at new Asset (/Users/mypath/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:1141)
    at Object.bind (/Users/mypath/node_modules/aws-cdk-lib/aws-s3-deployment/lib/source.js:1:1460)
    at BucketDeployment.addSource (/Users/mypath/node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:6709)
    at StackSetStackSynthesizer.addFileAsset (/Users/mypath/node_modules/cdk-stacksets/src/stackset-stack.ts:96:42)
    at new Asset (/Users/mypath/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:1623)
    at AssetCode.bind (/Users/mypath/node_modules/aws-cdk-lib/aws-lambda/lib/code.js:5:3487)
    at new Function (/Users/mypath/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:10003)
    at new NodejsFunction (/Users/mypath/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/function.js:1:2111)
    at new ScheduledReport (/Users/mypath/src/constructs/scheduled-reports/scheduled-report.ts:45:24)
```

**Comment by jtirrell-amazon** [comment]
> thanks for reporting this. i tested a nodejs function with the recent updates in #325 and it seems to work OK. there is an issue with python lambda with the s3 asset file name that gets produced that we will look into.

This is an issue that I am seeing, if I create the lambda function using the bundler the deployment is unable to find the file in the s3 bucket. 
ie:
`    const functionHandler = new cdk.aws_lambda.Function(this, "server", {
      code: cdk.aws_lambda.Code.fromAsset(`${lambdaSrcDir}/api/`,{
        bundling: {
        image: Runtime.PYTHON_3_12.bundlingImage,
        command: [
          'bash', '-c',
          'pip install -r requirements.txt -t /asset-output && cp -au . /asset-output'
        ],
      },
      }),
      handler: "server.lambda_handler",
      runtime: cdk.aws_lambda.Runtime.PYTHON_3_12,
      timeout: cdk.Duration.minutes(1),
      environment: {
        CLEAN_DATA_BUCKET: secureSightCleanBucket.bucketName,
        ORG_NAME: secureSightConfig.organizationName,
      },
      role: roleSecureSightServer,
    });`

**Comment by achernev** [comment]
I hit the same issue and discovered that if the bundling options are omitted, then the asset archive filename (the SHA256 one) will be identical to the one in the staging bucket. This is a workaround for the problem, if you can omit the bundling options or bundle the function code externally.

Example:

```python
# This produces error because the asset hash is different from the staging asset hash:
on_event_handler_function = lambda_.Function(
    self,
    id="OnEventFunction",
    function_name=on_event_handler_function_name,
    runtime=lambda_.Runtime.PYTHON_3_13,
    role=on_event_handler_role,
    code=lambda_.Code.from_asset(
        os.path.join(os.path.dirname(__file__), "lambda", "dependency_signal"),
        asset_hash="dependency_signal",
        bundling=BundlingOptions(
            image=lambda_.Runtime.PYTHON_3_13.bundling_image,
            command=[
                "bash",
                "-c",
                "pip install --no-cache-dir -r requirements.txt -t /asset-output && cp -au . /asset-output",
            ],
        ),
    ),
    timeout=Duration.minutes(5),
    log_retention=logs.RetentionDays.ONE_WEEK,
    handler="index.on_event",
)

# This DOES NOT produce error because the asset hash is identical to the staging asset hash:
on_event_handler_function = lambda_.Function(
    self,
    id="OnEventFunction",
    function_name=on_event_handler_function_name,
    runtime=lambda_.Runtime.PYTHON_3_13,
    role=on_event_handler_role,
    code=lambda_.Code.from_asset(os.path.join(os.path.dirname(__file__), "lambda", "dependency_signal")),
    timeout=Duration.minutes(5),
    log_retention=logs.RetentionDays.ONE_WEEK,
    handler="index.on_event",
)
```

Apologies if I am not using the correct terminology, I am fairly new to this.

**Comment by pahud** [comment]
Hi @mbergkvist,

```
┌──────────────────────────────┐     ┌────────────────────────────────────────────┐
│ Bundled asset staged once     │ ──> │ cdk-stacksets re-stages it from a LOCAL    │
│ hash H1, S3Key = H1.zip       │     │ path via Source.asset(`${outdir}/${file}`) │
└──────────────────────────────┘     └───────────────────┬────────────────────────┘
                                                         │
                          ┌──────────────────────────────┴────────────────────────┐
                          v                                                       v
┌──────────────────────────────────────────┐   ┌──────────────────────────────────────────┐
│ A: cdk list skips bundling, fileName is   │   │ B: second staging computes hash H2 from   │
│ ABSOLUTE -> "cdk.out/Users/…" ->          │   │ dir contents; H1 != H2 when assetHash /   │
│ CannotFindAsset                           │   │ SOURCE hash / exclude (*.pyc) is involved │
└──────────────────────────────────────────┘   │ -> uploads H2.zip, template wants H1.zip  │
                                               └──────────────────────────────────────────┘
```

Thanks to everyone who kept this thread alive. I spent some time on it and I believe the reason it has felt intermittent is that there are two separate bugs here, both in `StackSetStackSynthesizer.addFileAsset()`, and different people are hitting different ones. I reproduced both with `cdk synth`/`cdk list` alone (no deploy, no Docker) on cdk-stacksets 0.0.154 / aws-cdk-lib 2.268.0.

**A. `Cannot find asset at …/cdk.out/Users/…` on `cdk list`** (OP, @atali, @mgroff2). `cdk list` tells the CDK to skip bundling, and in that mode `AssetStaging` reports the asset's path as the *absolute source directory* (for `NodejsFunction` that is your project root, which is why the path ends in your project folder). cdk-stacksets then does `` `${outdir}/${asset.fileName}` ``, producing `cdk.out//Users/…`. `cdk synth --all` bundles for real, so the path is relative and it works — exactly what you observed.

https://github.com/cdklabs/cdk-stacksets/blob/51abb00f9e93224d3fb16835d34c0396eedf5a8f/src/stackset-stack.ts#L85-L86

https://github.com/aws/aws-cdk/blob/8fd1ef68c45418680a85987e00c6a1ea85701b27/packages/aws-cdk-lib/core/lib/asset-staging.ts#L333-L353

**B. S3 key mismatch for bundled functions** (OP's Python note, @josh-demuth, @jtirrell-amazon, @achernev). The StackSet template's `S3Key` is derived from the *original* asset hash, but the `BucketDeployment` re-stages the directory with `Source.asset()` and uploads it under a *newly computed* hash. Those two hashes only coincide when the original used `AssetHashType.OUTPUT` and no `exclude` pattern filtered the bundler's output — which is why plain esbuild `NodejsFunction` works and `PythonFunction` does not: `aws-lambda-python-alpha` passes `exclude: ['*.pyc']` while `pip` writes `__pycache__/*.pyc`, so the two fingerprints differ every time. Any `assetHash`/`assetHashType: SOURCE` with bundling breaks it the same way. I confirmed both variants; in each case `cdk.out` ends up with `asset.<H1>` and a second `asset.<H1>.<H2>` copy, and the template says `H1.zip` while the deployment uploads `H2.zip`. @achernev's finding that dropping bundling fixes it is consistent with this.

https://github.com/cdklabs/cdk-stacksets/blob/51abb00f9e93224d3fb16835d34c0396eedf5a8f/src/stackset-stack.ts#L104-L127

https://github.com/aws/aws-cdk/blob/f7ce07beb41b7fd0214a647b5a009f8706339105/packages/%40aws-cdk/aws-lambda-python-alpha/lib/bundling.ts#L63-L68

From my view both bugs share one root cause — re-staging an already-staged asset from a local path and re-deriving its hash — and the clean fix is to stop doing that: have the StackSetStack hand the asset to the parent stack's synthesizer and copy it with `Source.bucket()`, so there is a single staging and a single hash. That is what #881 implements, and in my opinion it should be reviewed with this issue (and #886, the Stage-nested cousin of A) in mind. If #881 stalls, a narrower patch would be `path.resolve()` for A plus pinning the re-staged asset's hash and reading the object key back from it for B; I've written that up in more detail and am happy to help with a PR either way.

Workaround until then: bundle outside CDK and use `Code.fromAsset(<prepared dir or zip>)` with no `bundling`/`exclude`/`assetHash`, and use `cdk synth --all` rather than `cdk list`.
