### ISSUE TITLE
Cannot perform aws_kms.Key.fromLookup in stacksets

### ISSUE THREAD

**Issue by jtirrell-amazon** [cdklabs/cdk-stacksets#564]
```
Error: Cannot retrieve value from context provider key-provider since account/region are not specified at the stack level. Configure "env" with an account and region when you define your stack.See https://docs.aws.amazon.com/cdk/latest/guide/environments.html for more details.
    at Function.getValue (/Users/jtirrell/Documents/git-repos/gitlab/wwps-lcc-proserve/delivery-kits/secure-sight-continuous-compliance/arch/cdk_build/node_modules/aws-cdk-lib/core/lib/context-provider.js:2:562)
    at Function.fromLookup (/Users/jtirrell/Documents/git-repos/gitlab/wwps-lcc-proserve/delivery-kits/secure-sight-continuous-compliance/arch/cdk_build/node_modules/aws-cdk-lib/aws-kms/lib/key.js:1:6753)
```

```
   const secureSightKmsKey = cdk.aws_kms.Key.fromLookup(
      this,
      "secureSightKmsKey",{
      aliasName: "alias/secureSightKmsKey"
      }
    );
```

I would expect, because the stack-set is targeted to an account / region that the env variable should be set so that I can perform these look-ups.

**Comment by McDoit** [comment]
I assume that any stack created by stacksets needs to be region agnostic, and therefore you can't provide account/region
One way would be to create your own lookup lambda (fromLookup is usually local to your code, not cloudformation)

**Comment by CraigLager** [comment]
I have the same issue when trying to import a VPC

```
Error: Cannot retrieve value from context provider vpc-provider since account/region are not specified at the stack level. Configure "env" with an account and region when you define your stack.See https://docs.aws.amazon.com/cdk/latest/guide/environments.html for more details.
```

Any workaround so that I can import a VPC into a stacksetstack would be very welcome at this point.

**Comment by pahud** [comment]
Hi @jtirrell-amazon,

```
┌──────────────────────────────┐     ┌──────────────────────────────────┐
│ Key.fromLookup() inside      │ ──> │ StackSetStack has no env         │
│ StackSetStack                │     │ (1 template, N accts × M regions)│
└──────────────────────────────┘     └───────────────┬──────────────────┘
                                                     v
                                     ┌──────────────────────────────────┐
                                     │ synth-time lookup impossible;    │
                                     │ resolve in each target at deploy │
                                     │ time (alias ARN / SSM parameter) │
                                     └──────────────────────────────────┘
```

Same root cause as #295, so I will keep this short and point there for the VPC case. I reproduced your error at synth with `cdk-stacksets@0.0.154` / `aws-cdk-lib@2.268.0`. It is by design: `StackSetStack` deliberately has no `env` because one template is deployed to every target account and region, and a `fromLookup` runs an API call at synth against a single environment and bakes that result into the template. Giving the stack an `env` would only move the failure to deploy time in every non-matching target.

https://github.com/cdklabs/cdk-stacksets/blob/51abb00f9e93224d3fb16835d34c0396eedf5a8f/src/stackset-stack.ts#L185-L188

For KMS there are two deploy-time patterns, both verified to synthesize a portable template:

```ts
// A) alias reference, no lookup needed; works for KmsMasterKeyId-style props
const alias = kms.Alias.fromAliasName(stackSetStack, 'Alias', 'alias/secureSightKmsKey');
new sqs.Queue(stackSetStack, 'Q', { encryptionMasterKey: alias });

// B) key ARN from each target's Parameter Store; use this when you need grants,
//    since IAM policies need the key ARN rather than the alias ARN
const keyArn = new CfnParameter(stackSetStack, 'KeyArn', {
  type: 'AWS::SSM::Parameter::Value<String>',
  default: '/secure-sight/kms-key-arn',
});
const key = kms.Key.fromKeyArn(stackSetStack, 'Key', keyArn.valueAsString);
key.grantEncryptDecrypt(role);
```

Option A renders `arn:${Partition}:kms:${Region}:${AccountId}:alias/secureSightKmsKey`, so each target resolves its own key; note imported aliases cannot be used with `grant*`. Option B has each target read `/secure-sight/kms-key-arn` from its own SSM Parameter Store when the stack instance is created, and the grant renders as `Resource: { Ref: KeyArn }`. If the target cannot be pre-seeded with a parameter, a small custom resource calling `kms:DescribeKey` in the target is the remaining option.

@CraigLager, the VPC equivalent (SSM-typed parameter of type `AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>` plus `Vpc.fromVpcAttributes`) is in #295:

https://github.com/cdklabs/cdk-stacksets/issues/295#issuecomment-5610855646

Closing this as a duplicate of #295, which stays open to track a README section on these patterns. A docs PR there would be welcome.
